@extends('central.layout')
@section('title','Platform Overview') @section('heading','Platform overview') @section('subheading','Subscriptions, activations and commercial health at a glance.')
@section('actions')<a class="btn" href="{{ route('central.register') }}">+ New business</a>@endsection
@section('content')
<div class="stats"><div class="stat"><span>Businesses</span><strong>{{ number_format($summary['businesses']) }}</strong><em>All tenant workspaces</em></div><div class="stat"><span>Pending activations</span><strong>{{ number_format($summary['pending_activation_requests']) }}</strong><em>Awaiting operator review</em></div><div class="stat"><span>Open SaaS invoices</span><strong>{{ number_format($summary['open_platform_invoices']) }}</strong><em>Issued or overdue</em></div><div class="stat"><span>Recorded revenue</span><strong>{{ number_format($summary['recorded_revenue_afn']) }}</strong><em>AFN received</em></div></div>
<div class="card"><div style="display:flex;justify-content:space-between;gap:14px;align-items:center;margin-bottom:15px"><div><strong>Businesses</strong><div class="muted">Trial and subscription status</div></div><span class="badge">{{ $pricing['trial_days'] }}-day trial · {{ number_format($pricing['renewal_afn']) }} AFN/year</span></div>
<div class="table-wrap"><table><thead><tr><th>Business</th><th>Owner</th><th>Subscription</th><th>Period end</th><th>Seller</th></tr></thead><tbody>
@forelse($businesses as $business)<tr><td><strong>{{ $business->display_name }}</strong><div class="muted">{{ $business->tenant_id }}</div></td><td>{{ $business->owner_name }}<div class="muted">{{ $business->owner_email }}</div></td><td>@php($status=$business->subscription?->status?->value ?? $business->subscription?->status ?? $business->status)<span class="badge {{ in_array($status,['active','trialing','trial'])?'ok':(in_array($status,['expired','suspended'])?'bad':'warn') }}">{{ ucfirst($status) }}</span></td><td>{{ $business->subscription?->current_period_end?->format('Y-m-d') ?? '—' }}</td><td>{{ $business->subscription?->seller?->name ?? '—' }}</td></tr>@empty<tr><td colspan="5" style="padding:35px;text-align:center;color:#64748b">No businesses yet.</td></tr>@endforelse
</tbody></table></div><div style="margin-top:14px">{{ $businesses->links() }}</div></div>
@endsection