<?php
use App\Models\Central\Tenant;
use Stancl\Tenancy\Database\Models\Domain;
return [
    'tenant_model'=>Tenant::class,
    'id_generator'=>Stancl\Tenancy\UUIDGenerator::class,
    'domain_model'=>Domain::class,
    'central_domains'=>[env('CENTRAL_DOMAIN','invoice.test')],
    'tenant_base_domain'=>env('TENANT_BASE_DOMAIN',env('CENTRAL_DOMAIN','invoice.test')),
    'bootstrappers'=>[
        Stancl\Tenancy\Bootstrappers\DatabaseTenancyBootstrapper::class,
        Stancl\Tenancy\Bootstrappers\CacheTenancyBootstrapper::class,
        Stancl\Tenancy\Bootstrappers\FilesystemTenancyBootstrapper::class,
        Stancl\Tenancy\Bootstrappers\QueueTenancyBootstrapper::class,
    ],
    'database'=>[
        'central_connection'=>env('DB_CONNECTION','mysql'),
        'template_tenant_connection'=>null,
        'prefix'=>env('TENANT_DB_PREFIX','invoice_tenant_'),
        'suffix'=>'',
        'managers'=>[
            'sqlite'=>Stancl\Tenancy\TenantDatabaseManagers\SQLiteDatabaseManager::class,
            'mysql'=>Stancl\Tenancy\TenantDatabaseManagers\MySQLDatabaseManager::class,
            'pgsql'=>Stancl\Tenancy\TenantDatabaseManagers\PostgreSQLDatabaseManager::class,
        ],
    ],
    'cache'=>['tag_base'=>'tenant'],
    'filesystem'=>[
        'suffix_base'=>'tenant',
        'disks'=>['local','public'],
        'root_override'=>['local'=>'%storage_path%/app/','public'=>'%storage_path%/app/public/'],
        'suffix_storage_path'=>true,
        'asset_helper_tenancy'=>false,
    ],
    'redis'=>['prefix_base'=>'tenant','prefixed_connections'=>[]],
    'features'=>[],
    'routes'=>true,
    'migration_parameters'=>[
        '--force'=>true,
        '--path'=>[database_path('migrations/tenant')],
        '--realpath'=>true,
    ],
];
